#!/bin/bash

set -e

if [[ -n "${pwd_fishway_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Build application for staging or a release.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pushd src/app

        # Run linter
        ./node_modules/.bin/eslint \
        src/ --ext .js --ext .jsx --max-warnings=0

        yarn build

        popd
    fi
fi
