#!/bin/bash

set -e

if [[ -n "${pwd_fishway_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Starts servers using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        if [ ! -f docker-compose.env ]
        then
            echo "Missing docker env file. Consult project README."
            exit 1
        fi
        docker-compose -f docker-compose.yml up
    fi
fi
